AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  VotingPokerRestApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      Name: VotingPokerRestApi
      StageName: Prod
      TracingEnabled: true

  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignInFunction
      Runtime: nodejs12.x
      CodeUri: ../build
      Handler: src/signin/index.handler
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !ImportValue GameStateTable
      ReservedConcurrentExecutions: 10
      Timeout: 10
      Environment:
        Variables:
          GAME_STATE_TABLE: !ImportValue GameStateTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /signin
            Method: POST
            RestApiId: !Ref VotingPokerRestApi
