AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: node12.x
    Timeout: 10
    Tracing: 'Active'
    CodeUri: ../build

Resources:
  VotingPokerWsApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: VotingPokerWsApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.message'

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VotingPokerWsApi
      RouteKey: $connect
      ApiKeyRequired: false
      AuthorizationType: NONE
      OperationName: Connect
      Target: !Sub
        - 'integrations/${Integration}'
        - Integration: !Ref ConnectIntegration

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VotingPokerWsApi
      RouteKey: $disconnect
      ApiKeyRequired: false
      AuthorizationType: NONE
      OperationName: Disconnect
      Target: !Sub
        - 'integrations/${Integration}'
        - Integration: !Ref DisconnectIntegration

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VotingPokerWsApi
      RouteKey: $default
      ApiKeyRequired: false
      AuthorizationType: NONE
      OperationName: Message
      Target: !Sub
        - 'integrations/${Integration}'
        - Integration: !Ref MessageIntegration

  VotingPokerDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref VotingPokerWsApi
      StageName: Prod

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VotingPokerWsApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - 'arn:aws:apigateway:${Region}/lambda/path/2015-03-31/functions/${FunctionArn}/invocations'
        - Region: !Ref AWS::Region
          FunctionArn: !GetAtt ConnectFunction.Arn

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VotingPokerWsApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - 'arn:aws:apigateway:${Region}/lambda/path/2015-03-31/functions/${FunctionArn}/invocations'
        - Region: !Ref AWS::Region
          FunctionArn: !GetAtt DisconnectFunction.Arn

  MessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VotingPokerWsApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - 'arn:aws:apigateway:${Region}/lambda/path/2015-03-31/functions/${FunctionArn}/invocations'
        - Region: !Ref AWS::Region
          FunctionArn: !GetAtt MessageFunction.Arn

  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ConnectFunction
      Handler: src/websocket/index.connect
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      ReservedConcurrentExecutions: 10

  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DisconnectFunction
      Handler: src/websocket/index.disconnect
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      ReservedConcurrentExecutions: 10

  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MessageFunction
      Handler: src/websocket/index.message
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      ReservedConcurrentExecutions: 30
